<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded("libtmrm")) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_libtmrm.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('libtmrm.so')) return;
    } else {
      if (!dl('libtmrm.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class libtmrm {
	const TMRM_TYPE_UNKNOWN = 0;

	const TMRM_TYPE_PROXY = 1;

	const TMRM_TYPE_LITERAL = 2;

	const TMRM_TYPE_MULTISET = 3;

	const TMRM_TYPE_ITERATOR = 4;

	const TMRM_TYPE_TUPLE = 5;

	const TMRM_TYPE_POINTER = 125;

	const TMRM_TYPE_STRING = 126;

	const TMRM_TYPE_HASH_DATUM = 127;

	const TMRM_ITERATOR_GET_METHOD_GET_OBJECT = 0;

	const TMRM_ITERATOR_GET_METHOD_GET_CONTEXT = 1;

	const TMRM_ITERATOR_GET_METHOD_GET_KEY = 2;

	const TMRM_ITERATOR_GET_METHOD_GET_VALUE = 3;

	static function tmrm_proxy_to_object($p) {
		return tmrm_proxy_to_object($p);
	}

	static function tmrm_literal_to_object($lit) {
		return tmrm_literal_to_object($lit);
	}

	static function tmrm_multiset_to_object($ms) {
		return tmrm_multiset_to_object($ms);
	}

	static function tmrm_iterator_to_object($ms) {
		return tmrm_iterator_to_object($ms);
	}

	static function tmrm_tuple_to_object($t) {
		return tmrm_tuple_to_object($t);
	}

	static function tmrm_object_get_type($object) {
		return tmrm_object_get_type($object);
	}

	static function tmrm_object_is_proxy($object) {
		return tmrm_object_is_proxy($object);
	}

	static function tmrm_object_is_literal($object) {
		return tmrm_object_is_literal($object);
	}

	static function tmrm_object_is_multiset($object) {
		return tmrm_object_is_multiset($object);
	}

	static function tmrm_object_is_iterator($object) {
		return tmrm_object_is_iterator($object);
	}

	static function tmrm_object_to_proxy($object) {
		return tmrm_object_to_proxy($object);
	}

	static function tmrm_object_to_literal($object) {
		return tmrm_object_to_literal($object);
	}

	static function tmrm_object_to_multiset($object) {
		return tmrm_object_to_multiset($object);
	}

	static function tmrm_object_to_iterator($object) {
		return tmrm_object_to_iterator($object);
	}

	static function tmrm_object_to_tuple($object) {
		return tmrm_object_to_tuple($object);
	}

	static function tmrm_object_free($object) {
		tmrm_object_free($object);
	}

	static function tmrm_subject_map_sphere_new() {
		return tmrm_subject_map_sphere_new();
	}

	static function tmrm_subject_map_sphere_free($sms) {
		tmrm_subject_map_sphere_free($sms);
	}

	static function tmrm_subject_map_new($sms,$storage,$label) {
		return tmrm_subject_map_new($sms,$storage,$label);
	}

	static function tmrm_subject_map_iterator($map) {
		return tmrm_subject_map_iterator($map);
	}

	static function tmrm_subject_map_proxies($map) {
		return tmrm_subject_map_proxies($map);
	}

	static function tmrm_subject_map_merge($map) {
		return tmrm_subject_map_merge($map);
	}

	static function tmrm_subject_map_export_to_yaml($map,$fh) {
		return tmrm_subject_map_export_to_yaml($map,$fh);
	}

	static function tmrm_subject_map_is_value_by_key($proxies,$key) {
		return tmrm_subject_map_is_value_by_key($proxies,$key);
	}

	static function tmrm_subject_map_name($map) {
		return tmrm_subject_map_name($map);
	}

	static function tmrm_subject_map_bottom($map) {
		return tmrm_subject_map_bottom($map);
	}

	static function tmrm_subject_map_import_from_yaml($map,$fh) {
		return tmrm_subject_map_import_from_yaml($map,$fh);
	}

	static function tmrm_subject_map_import_from_yaml_string($map,$str) {
		return tmrm_subject_map_import_from_yaml_string($map,$str);
	}

	static function tmrm_subject_map_free($m) {
		tmrm_subject_map_free($m);
	}

	static function tmrm_proxy_new($m) {
		return tmrm_proxy_new($m);
	}

	static function tmrm_proxy_by_label($map,$label) {
		return tmrm_proxy_by_label($map,$label);
	}

	static function tmrm_proxy_clone($p) {
		return tmrm_proxy_clone($p);
	}

	static function tmrm_proxy_update($p) {
		return tmrm_proxy_update($p);
	}

	static function tmrm_proxy_label($p) {
		return tmrm_proxy_label($p);
	}

	static function tmrm_proxy_keys($p) {
		return tmrm_proxy_keys($p);
	}

	static function tmrm_proxy_keys_by_value($p) {
		return tmrm_proxy_keys_by_value($p);
	}

	static function tmrm_proxy_values_by_key($proxy,$key) {
		return tmrm_proxy_values_by_key($proxy,$key);
	}

	static function tmrm_proxy_values_by_key_t($p,$key) {
		return tmrm_proxy_values_by_key_t($p,$key);
	}

	static function tmrm_proxy_is_value_by_key($p,$key) {
		return tmrm_proxy_is_value_by_key($p,$key);
	}

	static function tmrm_proxy_is_referenced($p) {
		return tmrm_proxy_is_referenced($p);
	}

	static function tmrm_proxy_remove($p) {
		return tmrm_proxy_remove($p);
	}

	static function tmrm_proxy_equals($p,$other) {
		return tmrm_proxy_equals($p,$other);
	}

	static function tmrm_proxy_add_property($p,$key,$value) {
		return tmrm_proxy_add_property($p,$key,$value);
	}

	static function tmrm_proxy_add_property_literal($p,$key,$value) {
		return tmrm_proxy_add_property_literal($p,$key,$value);
	}

	static function tmrm_proxy_remove_properties_by_key($p,$key) {
		return tmrm_proxy_remove_properties_by_key($p,$key);
	}

	static function tmrm_proxy_get_properties($p) {
		return tmrm_proxy_get_properties($p);
	}

	static function tmrm_proxy_add_type($p,$type) {
		return tmrm_proxy_add_type($p,$type);
	}

	static function tmrm_proxy_add_superclass($p,$superclass) {
		return tmrm_proxy_add_superclass($p,$superclass);
	}

	static function tmrm_proxy_subclasses($p) {
		return tmrm_proxy_subclasses($p);
	}

	static function tmrm_proxy_superclasses($p) {
		return tmrm_proxy_superclasses($p);
	}

	static function tmrm_proxy_direct_types($p) {
		return tmrm_proxy_direct_types($p);
	}

	static function tmrm_proxy_direct_instances($p) {
		return tmrm_proxy_direct_instances($p);
	}

	static function tmrm_proxy_direct_subclasses($p) {
		return tmrm_proxy_direct_subclasses($p);
	}

	static function tmrm_proxy_direct_superclasses($p) {
		return tmrm_proxy_direct_superclasses($p);
	}

	static function tmrm_proxy_sub($p,$class_p) {
		return tmrm_proxy_sub($p,$class_p);
	}

	static function tmrm_proxy_isa($p,$type) {
		return tmrm_proxy_isa($p,$type);
	}

	static function tmrm_proxy_free($p) {
		tmrm_proxy_free($p);
	}

	static function tmrm_literal_new($value,$datatype) {
		return tmrm_literal_new($value,$datatype);
	}

	static function tmrm_literal_datatype($lit) {
		return tmrm_literal_datatype($lit);
	}

	static function tmrm_literal_value($lit) {
		return tmrm_literal_value($lit);
	}

	static function tmrm_literal_is_value_by_key($lit,$key) {
		return tmrm_literal_is_value_by_key($lit,$key);
	}

	static function tmrm_literal_keys_by_value($lit,$map) {
		return tmrm_literal_keys_by_value($lit,$map);
	}

	static function tmrm_literal_free($lit) {
		tmrm_literal_free($lit);
	}

	static function tmrm_multiset_new($map) {
		return tmrm_multiset_new($map);
	}

	static function tmrm_multiset_new_from_iterator($map,$it) {
		return tmrm_multiset_new_from_iterator($map,$it);
	}

	static function tmrm_multiset_clone($ms) {
		return tmrm_multiset_clone($ms);
	}

	static function tmrm_multiset_insert($ms,$data) {
		return tmrm_multiset_insert($ms,$data);
	}

	static function tmrm_multiset_add($ms,$ms2) {
		return tmrm_multiset_add($ms,$ms2);
	}

	static function tmrm_multiset_size($ms) {
		return tmrm_multiset_size($ms);
	}

	static function tmrm_multiset_as_list($ms) {
		return tmrm_multiset_as_list($ms);
	}

	static function tmrm_multiset_free($ms) {
		tmrm_multiset_free($ms);
	}

	static function tmrm_iterator_new($sms,$context,$next_method,$end_method,$get_element_method,$free_method) {
		return tmrm_iterator_new($sms,$context,$next_method,$end_method,$get_element_method,$free_method);
	}

	static function tmrm_iterator_next($it) {
		return tmrm_iterator_next($it);
	}

	static function tmrm_iterator_end($it) {
		return tmrm_iterator_end($it);
	}

	static function tmrm_iterator_get_object($it) {
		return tmrm_iterator_get_object($it);
	}

	static function tmrm_iterator_get_key($it) {
		return tmrm_iterator_get_key($it);
	}

	static function tmrm_iterator_get_value($it) {
		return tmrm_iterator_get_value($it);
	}

	static function tmrm_iterator_free($it) {
		tmrm_iterator_free($it);
	}

	static function tmrm_storage_new($sms,$name,$params) {
		return tmrm_storage_new($sms,$name,$params);
	}

	static function tmrm_storage_free($s) {
		tmrm_storage_free($s);
	}
}

/* PHP Proxy Classes */

?>
