# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _libtmrm
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


TMRM_TYPE_UNKNOWN = _libtmrm.TMRM_TYPE_UNKNOWN
TMRM_TYPE_PROXY = _libtmrm.TMRM_TYPE_PROXY
TMRM_TYPE_LITERAL = _libtmrm.TMRM_TYPE_LITERAL
TMRM_TYPE_MULTISET = _libtmrm.TMRM_TYPE_MULTISET
TMRM_TYPE_ITERATOR = _libtmrm.TMRM_TYPE_ITERATOR
tmrm_object_get_type = _libtmrm.tmrm_object_get_type
tmrm_subject_map_sphere_new = _libtmrm.tmrm_subject_map_sphere_new
tmrm_subject_map_sphere_free = _libtmrm.tmrm_subject_map_sphere_free
tmrm_subject_map_new = _libtmrm.tmrm_subject_map_new
tmrm_subject_map_proxies = _libtmrm.tmrm_subject_map_proxies
tmrm_subject_map_is_value_by_key = _libtmrm.tmrm_subject_map_is_value_by_key
tmrm_subject_map_name = _libtmrm.tmrm_subject_map_name
tmrm_subject_map_free = _libtmrm.tmrm_subject_map_free
tmrm_proxy_new = _libtmrm.tmrm_proxy_new
tmrm_proxy_by_label = _libtmrm.tmrm_proxy_by_label
tmrm_proxy_clone = _libtmrm.tmrm_proxy_clone
tmrm_proxy_label = _libtmrm.tmrm_proxy_label
tmrm_proxy_keys = _libtmrm.tmrm_proxy_keys
tmrm_proxy_keys_by_value = _libtmrm.tmrm_proxy_keys_by_value
tmrm_proxy_values_by_key = _libtmrm.tmrm_proxy_values_by_key
tmrm_proxy_values_by_key_t = _libtmrm.tmrm_proxy_values_by_key_t
tmrm_proxy_is_value_by_key = _libtmrm.tmrm_proxy_is_value_by_key
tmrm_proxy_is_referenced = _libtmrm.tmrm_proxy_is_referenced
tmrm_proxy_remove = _libtmrm.tmrm_proxy_remove
tmrm_proxy_equals = _libtmrm.tmrm_proxy_equals
tmrm_proxy_add_property = _libtmrm.tmrm_proxy_add_property
tmrm_proxy_add_property_literal = _libtmrm.tmrm_proxy_add_property_literal
tmrm_proxy_remove_properties_by_key = _libtmrm.tmrm_proxy_remove_properties_by_key
tmrm_proxy_add_type = _libtmrm.tmrm_proxy_add_type
tmrm_proxy_add_superclass = _libtmrm.tmrm_proxy_add_superclass
tmrm_proxy_subclasses = _libtmrm.tmrm_proxy_subclasses
tmrm_proxy_superclasses = _libtmrm.tmrm_proxy_superclasses
tmrm_proxy_sub = _libtmrm.tmrm_proxy_sub
tmrm_proxy_isa = _libtmrm.tmrm_proxy_isa
tmrm_proxy_free = _libtmrm.tmrm_proxy_free
tmrm_literal_new = _libtmrm.tmrm_literal_new
tmrm_literal_datatype = _libtmrm.tmrm_literal_datatype
tmrm_literal_value = _libtmrm.tmrm_literal_value
tmrm_literal_is_value_by_key = _libtmrm.tmrm_literal_is_value_by_key
tmrm_literal_keys_by_value = _libtmrm.tmrm_literal_keys_by_value
tmrm_literal_free = _libtmrm.tmrm_literal_free
tmrm_multiset_new = _libtmrm.tmrm_multiset_new
tmrm_multiset_new_from_iterator = _libtmrm.tmrm_multiset_new_from_iterator
tmrm_multiset_insert = _libtmrm.tmrm_multiset_insert
tmrm_multiset_size = _libtmrm.tmrm_multiset_size
tmrm_multiset_as_list = _libtmrm.tmrm_multiset_as_list
tmrm_multiset_free = _libtmrm.tmrm_multiset_free
tmrm_iterator_new = _libtmrm.tmrm_iterator_new
tmrm_iterator_next = _libtmrm.tmrm_iterator_next
tmrm_iterator_end = _libtmrm.tmrm_iterator_end
tmrm_iterator_get_object = _libtmrm.tmrm_iterator_get_object
tmrm_iterator_free = _libtmrm.tmrm_iterator_free
tmrm_storage_new = _libtmrm.tmrm_storage_new
tmrm_storage_new_from_factory = _libtmrm.tmrm_storage_new_from_factory
tmrm_storage_free = _libtmrm.tmrm_storage_free
tmrm_storage_init = _libtmrm.tmrm_storage_init
tmrm_storage_add_property = _libtmrm.tmrm_storage_add_property
tmrm_storage_add_property_literal = _libtmrm.tmrm_storage_add_property_literal
tmrm_storage_remove_properties_by_key = _libtmrm.tmrm_storage_remove_properties_by_key
tmrm_storage_proxy_by_label = _libtmrm.tmrm_storage_proxy_by_label
tmrm_storage_proxy_label = _libtmrm.tmrm_storage_proxy_label
tmrm_storage_proxies = _libtmrm.tmrm_storage_proxies
tmrm_storage_proxy_keys = _libtmrm.tmrm_storage_proxy_keys
tmrm_storage_proxy_values_by_key = _libtmrm.tmrm_storage_proxy_values_by_key
tmrm_storage_proxy_keys_by_value = _libtmrm.tmrm_storage_proxy_keys_by_value
tmrm_storage_proxy_remove = _libtmrm.tmrm_storage_proxy_remove
tmrm_storage_proxy_add_type = _libtmrm.tmrm_storage_proxy_add_type
tmrm_storage_proxy_add_superclass = _libtmrm.tmrm_storage_proxy_add_superclass
tmrm_storage_proxy_direct_subclasses = _libtmrm.tmrm_storage_proxy_direct_subclasses
tmrm_storage_proxy_direct_superclasses = _libtmrm.tmrm_storage_proxy_direct_superclasses
tmrm_storage_proxy_direct_types = _libtmrm.tmrm_storage_proxy_direct_types
tmrm_storage_proxy_is_value_by_key = _libtmrm.tmrm_storage_proxy_is_value_by_key
tmrm_storage_literal_is_value_by_key = _libtmrm.tmrm_storage_literal_is_value_by_key
tmrm_storage_literal_keys_by_value = _libtmrm.tmrm_storage_literal_keys_by_value
tmrm_init_storage_pgsql = _libtmrm.tmrm_init_storage_pgsql
tmrm_init_storage_db = _libtmrm.tmrm_init_storage_db


