/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_LIBTMRM_H
#define PHP_LIBTMRM_H

extern zend_module_entry libtmrm_module_entry;
#define phpext_libtmrm_ptr &libtmrm_module_entry

#ifdef PHP_WIN32
# define PHP_LIBTMRM_API __declspec(dllexport)
#else
# define PHP_LIBTMRM_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(libtmrm);
PHP_MSHUTDOWN_FUNCTION(libtmrm);
PHP_RINIT_FUNCTION(libtmrm);
PHP_RSHUTDOWN_FUNCTION(libtmrm);
PHP_MINFO_FUNCTION(libtmrm);

ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_to_object);
ZEND_NAMED_FUNCTION(_wrap_tmrm_literal_to_object);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_to_object);
ZEND_NAMED_FUNCTION(_wrap_tmrm_iterator_to_object);
ZEND_NAMED_FUNCTION(_wrap_tmrm_tuple_to_object);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_get_type);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_is_proxy);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_is_literal);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_is_multiset);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_is_iterator);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_to_proxy);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_to_literal);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_to_multiset);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_to_iterator);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_to_tuple);
ZEND_NAMED_FUNCTION(_wrap_tmrm_object_free);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_sphere_new);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_sphere_free);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_new);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_iterator);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_proxies);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_merge);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_export_to_yaml);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_is_value_by_key);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_name);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_bottom);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_import_from_yaml);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_import_from_yaml_string);
ZEND_NAMED_FUNCTION(_wrap_tmrm_subject_map_free);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_new);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_by_label);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_clone);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_update);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_label);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_keys);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_keys_by_value);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_values_by_key);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_values_by_key_t);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_is_value_by_key);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_is_referenced);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_remove);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_equals);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_add_property);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_add_property_literal);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_remove_properties_by_key);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_get_properties);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_add_type);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_add_superclass);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_subclasses);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_superclasses);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_direct_types);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_direct_instances);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_direct_subclasses);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_direct_superclasses);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_sub);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_isa);
ZEND_NAMED_FUNCTION(_wrap_tmrm_proxy_free);
ZEND_NAMED_FUNCTION(_wrap_tmrm_literal_new);
ZEND_NAMED_FUNCTION(_wrap_tmrm_literal_datatype);
ZEND_NAMED_FUNCTION(_wrap_tmrm_literal_value);
ZEND_NAMED_FUNCTION(_wrap_tmrm_literal_is_value_by_key);
ZEND_NAMED_FUNCTION(_wrap_tmrm_literal_keys_by_value);
ZEND_NAMED_FUNCTION(_wrap_tmrm_literal_free);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_new);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_new_from_iterator);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_clone);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_insert);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_add);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_size);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_as_list);
ZEND_NAMED_FUNCTION(_wrap_tmrm_multiset_free);
ZEND_NAMED_FUNCTION(_wrap_tmrm_iterator_new);
ZEND_NAMED_FUNCTION(_wrap_tmrm_iterator_next);
ZEND_NAMED_FUNCTION(_wrap_tmrm_iterator_end);
ZEND_NAMED_FUNCTION(_wrap_tmrm_iterator_get_object);
ZEND_NAMED_FUNCTION(_wrap_tmrm_iterator_get_key);
ZEND_NAMED_FUNCTION(_wrap_tmrm_iterator_get_value);
ZEND_NAMED_FUNCTION(_wrap_tmrm_iterator_free);
ZEND_NAMED_FUNCTION(_wrap_tmrm_storage_new);
ZEND_NAMED_FUNCTION(_wrap_tmrm_storage_free);
#endif /* PHP_LIBTMRM_H */
